name: Build
on:
  push:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js 20.x
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
      - name: Install dependencies
        working-directory: ./akiyuki
        run: npm ci
      - name: Install Quasar CLI
        working-directory: ./akiyuki
        run: npm install -g @quasar/cli
      - name: Build
        working-directory: ./akiyuki
        run: npm run build
      - name: Preparation for static site
        run: |
          cp ./docs/index.html ./docs/snake
          cp ./docs/index.html ./docs/boids-algorithm
      - name: Commit and push changes
        run: |
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'github-actions@github.com'
          git add .
          git diff --quiet && git diff --staged --quiet || (git commit -m "Automated changes by GitHub Actions" && git push)
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
