name: Build
on:
  push:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js 18.x
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'
      - name: install dependencies
        working-directory: ./akiyuki
        run: npm install
      - name: Install Quasar CLI
        working-directory: ./akiyuki
        run: npm install -g @quasar/cli
      - name: Build
        working-directory: ./akiyuki
        run: npm run build
      - name: Preparation for static site
        run: cp ./docs/index.html ./docs/snake
        run: cp ./docs/index.html ./docs/boids-algorithm
      - name: Commit and push changes
        run: |
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'github-actions@github.com'
          git add .
          git commit -m "Automated changes by GitHub Actions"
          git push
