name: Build and Deploy
on:
  push:
    branches:
      - main  # ビルドをトリガーするブランチを指定します

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies and build
        run: |
<<<<<<< HEAD
          npm install
=======
>>>>>>> 69893b93d8bb570b9d631d892c085f4d1b039451
          npm ci
          npm run build

      - name: Copy index.html
        run: |
          mkdir docs/snake
          cp docs/index.html snake/
